#!/bin/bash
#DEBHELPER#
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

DEEPSPEECH_DIR=/usr/share/deepspeech

if [ ! -d "$DEEPSPEECH_DIR" ]; then
  mkdir $DEEPSPEECH_DIR
fi
if [ ! -d "${DEEPSPEECH_DIR}/models" ]; then
  cd $DEEPSPEECH_DIR
  wget -nc -O - https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz | tar xvfz -
fi


pip3 install wikipedia PyUserInput tinydb youtube_dl spacy pyowm && pip3 install -U PyAudio && python3 -m spacy download en \
&& printf "import nltk\nnltk.download('names')\nnltk.download('brown')\nnltk.download('wordnet')" | python3 && echo -e "\n\n${GREEN}Dragonfire is successfully installed to your computer.${NC}\n"
