#!/bin/bash
#DEBHELPER#
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
CHECKSUM="1449d83e0a0b834c033067bf62f06277"
CHECKSUM2="c775d819ffc06118053a48808003df84"

DRAGONFIRE_DIR=/usr/share/dragonfire
if [ ! -d "$DRAGONFIRE_DIR" ]; then
  mkdir $DRAGONFIRE_DIR
fi

DEEPSPEECH_DIR=/usr/share/dragonfire/deepspeech
if [ ! -d "$DEEPSPEECH_DIR" ]; then
  mkdir $DEEPSPEECH_DIR
fi
cd $DEEPSPEECH_DIR
verified=$(md5sum models/* | md5sum)
if [ ! ${verified::-3} = "$CHECKSUM" ]; then
  wget -nc -O - https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz | tar xvfz -
fi

DEEPCONV_DIR=/usr/share/dragonfire/deepconv
if [ ! -d "$DEEPCONV_DIR" ]; then
  mkdir $DEEPCONV_DIR
fi
cd $DEEPCONV_DIR
verified=$(find . -type f -exec md5sum {} \; | md5sum)
if [ ! ${verified::-3} = "$CHECKSUM2" ]; then
  wget -nc -O - https://github.com/DragonComputer/Dragonfire/releases/download/v0.9.9/deepconv-v2.tar.gz | tar xvfz -
fi


pip3 install --upgrade wikipedia==1.4.0 PyUserInput==0.1.11 tinydb==3.9.0.post1 youtube_dl spacy==2.0.11 pyowm==2.9.0 tensorflow==1.0.0 deepspeech==0.2.0a5 SpeechRecognition tweepy==3.6.0 metadata_parser==0.9.20 hug==2.4.0 hug-middleware-cors==1.0.0 waitress==1.1.0 requests==2.19.1 pyjwt==1.6.4 SQLAlchemy==1.2.10 PyMySQL==0.8.1 && \
python3 -m spacy download en && \
pip3 install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz && \
printf "import nltk\nnltk.download('names')\nnltk.download('brown')\nnltk.download('wordnet')\nnltk.download('punkt')" | python3 && echo -e "\n\n${GREEN}Dragonfire is successfully installed to your computer.${NC}\n"
