class Config():
    # Twitter Credentials
    TWITTER_CONSUMER_KEY = 'CONSUMER_KEY'
    TWITTER_CONSUMER_SECRET = 'CONSUMER_SECRET'
    TWITTER_ACCESS_KEY = 'ACCESS_KEY'
    TWITTER_ACCESS_SECRET = 'ACCESS_SECRET'

    # MySQL Credentials
    MYSQL_HOST = 'MYSQL_HOST'
    MYSQL_DB = 'MYSQL_DB'
    MYSQL_USER = 'MYSQL_USER'
    MYSQL_PASS = 'MYSQL_PASS'
